// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfpaugarolblhuimgmdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcGF1Z2Fyb2xibGh1aW1nbWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTI0NzQsImV4cCI6MjA3MTI4ODQ3NH0.m_wtsbqq9IZviYlRy1I2BQxvpWTEcnOC2DtY8RrRr0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});